In [2]:
import pandas as pd
import matplotlib.pyplot as plt
from scipy.linalg import svd
from numpy import array
import random
df = pd.read_csv("iris.csv")

In [3]:
print(df["SepalLengthCm"][0:7])
    

0    5.1
1    4.9
2    4.7
3    4.6
4    5.0
5    5.4
6    4.6
Name: SepalLengthCm, dtype: float64


In [4]:
# taking basic sample of first 7 instances of the dataset
se = set()
while(len(se) < 8):
    se.add(random.randint(1,151))
sl = []
sw = []
pl = []
pw = []
for i in se:
    sl.append(df["SepalLengthCm"][i-1])
    sw.append(df["SepalWidthCm"][i-1])
    pl.append(df["PetalLengthCm"][i-1])
    pw.append(df["PetalWidthCm"][i-1])
    
l = [sl,sw,pl,pw]
print(l)

[[6.1, 7.1, 4.4, 6.8, 6.7, 5.5, 6.4, 6.6], [2.9, 3.0, 2.9, 2.8, 3.0, 2.4, 3.2, 2.9], [4.7, 5.9, 1.4, 4.8, 5.0, 3.8, 5.3, 4.6], [1.4, 2.1, 0.2, 1.4, 1.7, 1.1, 2.3, 1.3]]


In [5]:
# 0 : Iris-setosa
# 1 : Iris-versicolor
# 2 : Iris-virginica
x = []
for i in se:
    if(df["Species"][i] == "Iris-setosa"):
        x.append(0)
    elif(df["Species"][i] == "Iris-versicolor"):
        x.append(1)
    else:
        x.append(2)
l.append(x)

In [6]:
print(l)

[[6.1, 7.1, 4.4, 6.8, 6.7, 5.5, 6.4, 6.6], [2.9, 3.0, 2.9, 2.8, 3.0, 2.4, 3.2, 2.9], [4.7, 5.9, 1.4, 4.8, 5.0, 3.8, 5.3, 4.6], [1.4, 2.1, 0.2, 1.4, 1.7, 1.1, 2.3, 1.3], [1, 2, 0, 1, 1, 1, 2, 1]]


In [7]:
U,s,VT = svd(array(l))
print(array(l))

[[6.1 7.1 4.4 6.8 6.7 5.5 6.4 6.6]
 [2.9 3.  2.9 2.8 3.  2.4 3.2 2.9]
 [4.7 5.9 1.4 4.8 5.  3.8 5.3 4.6]
 [1.4 2.1 0.2 1.4 1.7 1.1 2.3 1.3]
 [1.  2.  0.  1.  1.  1.  2.  1. ]]


In [8]:
print(U)
print(s)
print(VT)

[[ 0.73609977  0.37678544  0.24576693  0.37414681 -0.34029787]
 [ 0.3370179   0.45511781 -0.64062867 -0.37207846  0.36116375]
 [ 0.54112708 -0.55266439  0.32716783 -0.33304864  0.42869962]
 [ 0.17841809 -0.39037666 -0.37810968 -0.37365714 -0.73019618]
 [ 0.14115428 -0.43939577 -0.52838226  0.68631679  0.19180271]]
[23.99272101  2.49914255  0.94380607  0.39695271  0.21280018]
[[ 0.3501811   0.42041911  0.20879051  0.3725079   0.37899089  0.30222036
   0.38970734  0.36252215]
 [ 0.01391961 -0.36763505  0.8506486   0.07913061  0.00938635  0.078294
  -0.33530514  0.12703714]
 [ 0.12853074 -0.10324737 -0.4174964   0.41335249  0.200701    0.1198807
  -0.70939436  0.26412814]
 [-0.50097612  0.41106545  0.06605044  0.16863953 -0.5632795   0.43967009
  -0.12103999  0.14833039]
 [ 0.73296034  0.22038289  0.01975774 -0.35470286 -0.48184746  0.060151
  -0.21579035  0.07506955]
 [-0.05719487 -0.10152859 -0.07773944 -0.53250442  0.36339773  0.73418033
  -0.08410164 -0.13661831]
 [ 0.12169648 -0.6694

In [9]:
print(U)

[[ 0.73609977  0.37678544  0.24576693  0.37414681 -0.34029787]
 [ 0.3370179   0.45511781 -0.64062867 -0.37207846  0.36116375]
 [ 0.54112708 -0.55266439  0.32716783 -0.33304864  0.42869962]
 [ 0.17841809 -0.39037666 -0.37810968 -0.37365714 -0.73019618]
 [ 0.14115428 -0.43939577 -0.52838226  0.68631679  0.19180271]]


In [10]:
print(s)

[23.99272101  2.49914255  0.94380607  0.39695271  0.21280018]


In [11]:
print(s[4])

0.21280017974901233


In [12]:
print(VT)

[[ 0.3501811   0.42041911  0.20879051  0.3725079   0.37899089  0.30222036
   0.38970734  0.36252215]
 [ 0.01391961 -0.36763505  0.8506486   0.07913061  0.00938635  0.078294
  -0.33530514  0.12703714]
 [ 0.12853074 -0.10324737 -0.4174964   0.41335249  0.200701    0.1198807
  -0.70939436  0.26412814]
 [-0.50097612  0.41106545  0.06605044  0.16863953 -0.5632795   0.43967009
  -0.12103999  0.14833039]
 [ 0.73296034  0.22038289  0.01975774 -0.35470286 -0.48184746  0.060151
  -0.21579035  0.07506955]
 [-0.05719487 -0.10152859 -0.07773944 -0.53250442  0.36339773  0.73418033
  -0.08410164 -0.13661831]
 [ 0.12169648 -0.66945213 -0.21495375  0.16803765 -0.35191458  0.29221641
   0.40499872  0.29887086]
 [-0.2331739   0.03761107 -0.03871276 -0.46697422  0.10312302 -0.2585003
  -0.01204543  0.80439411]]
